### ISSUE TITLE
[Feature] Visualization of SR lifetime 

### ISSUE THREAD

**Issue by mikeplavsky** [skalitin/Armadillo#7]
Given: 
- SR A exists two days and SR B - 1 month
- Both SR are identical by other parameters 

When looking at the app the operator should be able to get the difference in the SRs lifetime quickly

**Comment by skalitin** [comment]
Done: 
![image](https://user-images.githubusercontent.com/393726/54186313-2b269500-44bc-11e9-90bc-479d75dd52b4.png)
